/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e4e1ed",
        "on-secondary": "#2f3130",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "surface": "#12131b",
        "on-secondary-fixed-variant": "#454746",
        "inverse-primary": "#4649db",
        "inverse-on-surface": "#303039",
        "surface-dim": "#12131b",
        "on-secondary-container": "#b4b5b4",
        "on-error": "#690005",
        "on-tertiary": "#2e3036",
        "tertiary": "#c6c6cd",
        "surface-container": "#1f1f28",
        "surface-container-low": "#1b1b23",
        "outline": "#908fa0",
        "surface-tint": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "surface-variant": "#34343d",
        "on-background": "#e4e1ed",
        "on-surface-variant": "#c6c5d7",
        "background": "#12131b",
        "outline-variant": "#464555",
        "tertiary-container": "#707178",
        "on-primary-container": "#faf6ff",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#1a1b21",
        "error": "#ffb4ab",
        "primary": "#c0c1ff",
        "primary-container": "#5b5ff0",
        "secondary-fixed-dim": "#c6c7c5",
        "on-primary-fixed-variant": "#2b2bc4",
        "secondary-container": "#454746",
        "on-primary": "#0e00aa",
        "tertiary-fixed": "#e2e2e9",
        "on-surface": "#e4e1ed",
        "error-container": "#93000a",
        "secondary-fixed": "#e2e3e1",
        "on-tertiary-container": "#f7f7fe",
        "tertiary-fixed-dim": "#c6c6cd",
        "on-primary-fixed": "#05006c",
        "on-tertiary-fixed-variant": "#45474d",
        "secondary": "#c6c7c5",
        "surface-bright": "#393842",
        "surface-container-lowest": "#0d0d16",
        "on-secondary-fixed": "#1a1c1b",
        "primary-fixed-dim": "#c0c1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "unit": "8px"
      },
      fontFamily: {
        body: ["Geist", "sans-serif"],
        headline: ["Geist", "sans-serif"],
      }
    },
  },
  plugins: [],
}
